"""
Implementation of fully async training in SkyRL.

For details, see https://docs.skyrl.ai/docs/tutorials/fully_async.

High-level notes:
- The global_step in each training loop iteration denotes the "current step being worked on", so
`global_step - 1` is the number of steps the model has finished training.
- We do not do any cross-epoch asynchrony here, so all the control logics like
  generation workers and data buffer are initialized per-epoch. The async dataloader
  and staleness manager are also reset / validated at the end of each epoch.
"""

import asyncio
import copy
import inspect
import os
import threading
import time
from dataclasses import dataclass
from typing import Any, Iterable, List, Optional, Set, Tuple

import torch
from loguru import logger
from torchdata.stateful_dataloader import StatefulDataLoader
from tqdm import tqdm

from skyrl.backends.skyrl_train.inference_servers.engine_utils import (
    get_sampling_params_for_backend,
)
from skyrl.backends.skyrl_train.training_batch import TrainingInputBatch
from skyrl.backends.skyrl_train.utils.io import io
from skyrl.backends.skyrl_train.utils.ppo_utils import (
    LOSSES_WITH_OLD_LOGPROBS,
    PolicyLossType,
)
from skyrl.train.generators.base import GeneratorOutput
from skyrl.train.generators.utils import (
    concatenate_generator_outputs,
    get_metrics_from_generator_output,
    prepare_generator_input,
)
from skyrl.train.trainer import RayPPOTrainer
from skyrl.train.utils import Timer
from skyrl.train.utils.metrics import ScalarGauges, TrainingPhaseGauge
from skyrl.train.utils.progress_events import emit_progress_event
from skyrl.train.utils.trainer_utils import (
    ResumeMode,
    build_dataloader,
    get_group_completion_metrics,
    get_intra_group_completion_time_std_cv,
    zero_variance_filter,
)


@dataclass
class GeneratedOutputGroup:
    """
    The GeneratorOutput for a single group of rollouts, along with the metadata.

    Attributes:
        generator_output (GeneratorOutput): The GeneratorOutput for a single group of rollouts.
            That is, the output to the same prompt, but `n_samples_per_prompt` of it.

        uid (str): The uid of the group. Underlyingly, it is the index of the data in train_dataloader.dataset.

        global_step_when_scheduled (int): The global step when the group was scheduled for generation,
            used for staleness control when the inference backend does not
            report an exact sampler version.

        group_completion_time_s (Optional[float]): Wall-clock time (seconds) for the whole group to
            finish generation, i.e. the time for the slowest trajectory in the group to complete.
            None if generation timing was not captured.

        prompts (Optional[List[Any]]): The generator input prompts (in OpenAI message format) for this
            group, one per trajectory (parallel to ``generator_output["response_ids"]``). Retained so
            the trajectory logger can render prompt + response, mirroring the synchronous trainer which
            logs ``generator_input["prompts"]``. None if not captured.
    """

    generator_output: GeneratorOutput
    uid: str
    global_step_when_scheduled: int
    group_completion_time_s: Optional[float] = None
    prompts: Optional[List[Any]] = None


@dataclass
class _RolloutStat:
    """
    Global statistics of the trajectories used for staleness control in `_AsyncStalenessManager`.

    Note that these statistics are not per-epoch, but accumulates across all epochs.

    Attributes:
        submitted (int): The number of trajectories submitted to all generation workers, only used
            for logging purposes (e.g. compute submitted / accepted ratio to see how many
            trajectories failed). This is strictly increasing.
        accepted (int): The number of trajectories finished generation that will be trained on (either
            already consumed by, or about to be consumed by the training worker). This is strictly
            increasing in the absence of filtering; ``on_rollout_filtered`` decrements it when an
            already-generated group is dropped from training (see ``sample_full_batch``).
        running (int): The number of trajectories currently being generated by the generation workers.
        filtered (int): The number of finished trajectories that were dropped from training (e.g.
            zero-variance groups under ``sample_full_batch``). This is strictly increasing. The
            invariant ``submitted == accepted + filtered + running`` always holds.

    For details, see https://docs.skyrl.ai/docs/tutorials/fully_async#async-staleness-manager
    """

    submitted: int = 0
    accepted: int = 0
    running: int = 0
    filtered: int = 0


def _advance_global_step_after_training(global_step: int, max_training_steps: Optional[int]) -> tuple[int, bool]:
    """Return the next step cursor and whether the configured cap was reached.

    Keep the cursor on the last completed step when stopping so a final
    checkpoint resumes from the following step instead of skipping it.
    """

    if max_training_steps is not None and global_step >= max_training_steps:
        return global_step, True
    return global_step + 1, False


def _needs_final_checkpoint(
    ckpt_interval: int,
    completed_step: int,
    last_checkpoint_step: Optional[int],
) -> bool:
    """Save a completed step once; a next-step cursor is never checkpointable."""

    return ckpt_interval > 0 and completed_step > 0 and last_checkpoint_step != completed_step


class _AsyncStalenessManager:
    """
    A controller that manages the capacity of the generation workers based on staleness control.

    The goal is to never submit more trajectories to the generation workers than the training worker
    can consume, so that the trajectories are not too stale (relative to max_staleness_steps).
    This is enforced via a capacity rule, not a hard **per-group** staleness guarantee: we bound
    the **aggregate** number of groups that can be ahead of training so that, in **steady state**,
    staleness remains within the configured budget of `max_staleness_steps`.

    In pathological cases (e.g., very long-running trajectories), an individual group may take
    more than `max_staleness_steps` of training steps of time to finish generation. For such rare
    cases, we still accept the trajectory and log the staleness metrics with a warning.

    The key capacity formula is implemented in `_compute_capacity_unlocked`. For details and caveats,
    see https://docs.skyrl.ai/docs/tutorials/fully_async#async-staleness-manager.

    Reference:
    - Modeled after AReal's StalenessManager: https://github.com/inclusionAI/AReaL/blob/b755c4447c2fff97889d8828293ee85f17a806f9/areal/core/staleness_manager.py
    - The idea of this controller is from section 5.1 of AReal's paper: https://arxiv.org/pdf/2505.24298v3
    """

    def __init__(
        self,
        max_concurrent_generation_groups: int,
        mini_batch_size: int,
        max_staleness_steps: int,
    ):
        self.max_concurrent_generation_groups = max_concurrent_generation_groups
        self.mini_batch_size = mini_batch_size
        self.max_staleness_steps = max_staleness_steps

        # Control logics.
        self._stat = _RolloutStat()
        self._cond = asyncio.Condition()

        # The current version that is being worked on, i.e. FullyAsyncRayPPOTrainer.global_step.
        # `self._current_global_step - 1` is the number of steps the model has finished training.
        self._current_global_step = 1

    def load_state_from_checkpoint(self, global_step: int) -> None:
        """
        Load the state from a checkpoint.
        """
        self._current_global_step = global_step
        # trainer has already consumed (and hence submitted) this many trajectories.
        self._stat.accepted = (global_step - 1) * self.mini_batch_size
        self._stat.submitted = self._stat.accepted

    async def validate_state_at_epoch_end(self, global_step: int) -> None:
        """
        Check that the current version and accepted rollouts are consistent with the global step.

        Args:
            global_step: The global step we are about to train on (after incrementing).
        """
        async with self._cond:
            assert self._stat.running == 0, "We expect no rollouts are running at end of an epoch."
            consumed = (global_step - 1) * self.mini_batch_size
            assert (
                self._stat.accepted == consumed
            ), f"Unexpected number of accepted rollouts. Got {self._stat.accepted} != {consumed}."
            assert (
                self._current_global_step == global_step
            ), f"Unexpected current version. Got {self._current_global_step} != {global_step}."
            # All submitted rollouts must have finished as either accepted (trained) or filtered (dropped).
            assert self._stat.submitted == self._stat.accepted + self._stat.filtered, (
                "We expect all submitted rollouts to be accepted or filtered at end of an epoch. "
                f"Got {self._stat.submitted} != {self._stat.accepted} + {self._stat.filtered}."
            )

    def _compute_capacity_unlocked(self) -> int:
        # NOTE(Charlie): do not need a self._current_global_step + 1 here unlike AReal because our
        # `_current_global_step` is "the version being worked on", not already finished steps.
        consumer_capacity = (self.max_staleness_steps + self._current_global_step) * self.mini_batch_size
        producer_staleness_capacity = consumer_capacity - (self._stat.accepted + self._stat.running)
        producer_concurrency_capacity = self.max_concurrent_generation_groups - self._stat.running
        return min(producer_concurrency_capacity, producer_staleness_capacity)

    async def acquire_submission_slot(self) -> None:
        """Block until there is capacity, then reserve a slot (increments submitted and running).

        This method always uses the latest current version tracked internally, which is
        updated by `notify_capacity_change(new_global_step)`.
        """
        async with self._cond:
            while self._compute_capacity_unlocked() <= 0:
                await self._cond.wait()
            # Reserve slot
            self._stat.submitted += 1
            self._stat.running += 1

    async def on_rollout_accepted(self) -> None:
        async with self._cond:
            self._stat.accepted += 1
            self._stat.running -= 1
            self._cond.notify_all()

    async def on_rollout_filtered(self) -> None:
        """Reclassify an already-accepted group as filtered when it is dropped from training.

        Without this, dropped groups keep counting toward ``accepted`` while ``current_global_step``
        only advances on trained steps, shrinking producer capacity on every drop -> deadlock.
        """
        async with self._cond:
            self._stat.accepted -= 1
            self._stat.filtered += 1
            self._cond.notify_all()

    async def on_rollout_rejected(self) -> None:
        """Release a slot when a generation worker fails or is cancelled before acceptance."""
        async with self._cond:
            self._stat.running -= 1
            self._cond.notify_all()

    async def notify_capacity_change(self, new_global_step: int) -> None:
        # Called when current_global_step changes (e.g., after a training step)
        async with self._cond:
            self._current_global_step = int(new_global_step)
            self._cond.notify_all()


class _AsyncDataloader:
    """
    A train dataloader wrapper that accommodates the need of fully async training, including:
    - Thread-safe dataloader iteration with a lock, as there are multiple parallel generation workers polling data.
    - Records consumed data UIDs for checkpointing to avoid training on the same data upon resuming.
    - Set the effective dataloader length to be divisible by mini-batch size, since we cannot rely on `drop_last`
      because the batch size is 1 in fully async training.
    """

    def __init__(self, train_dataloader: StatefulDataLoader, mini_batch_size: int):
        self._train_dataloader = train_dataloader
        self._train_dataloader_initial_state = copy.deepcopy(train_dataloader.state_dict())
        self._epoch_start_dataloader_state = copy.deepcopy(
            self._train_dataloader_initial_state
        )
        self._effective_dataloader_length = len(self._train_dataloader) // mini_batch_size * mini_batch_size
        self._iter = enumerate(self._train_dataloader)
        self._lock: asyncio.Lock = asyncio.Lock()
        # `_consumed_data_uids` = do-not-redraw set (trained ∪ filtered); `_filtered_data_uids` =
        # the dropped (not trained) subset. Both persisted so dropped prompts aren't regenerated on
        # resume; trained count is `len(consumed) - len(filtered)`.
        self._consumed_data_uids: Set[str] = set()
        self._filtered_data_uids: Set[str] = set()
        self._exhausted: bool = False  # currently not used.

    def load_state_from_checkpoint(
        self,
        consumed_data_uids_set: Set[str],
        filtered_data_uids_set: Optional[Set[str]] = None,
        epoch_start_dataloader_state: Optional[dict] = None,
    ) -> None:
        """
        Load the state from a checkpoint.
        """
        self._consumed_data_uids = consumed_data_uids_set
        self._filtered_data_uids = filtered_data_uids_set if filtered_data_uids_set is not None else set()

        # The common checkpoint captures the live loader position, which may be
        # ahead of completed training due to async prefetch. Restore the saved
        # epoch-start sampler state and skip completed/filtered UIDs instead.
        epoch_start_state = (
            self._train_dataloader_initial_state
            if epoch_start_dataloader_state is None
            else epoch_start_dataloader_state
        )
        self._train_dataloader.load_state_dict(copy.deepcopy(epoch_start_state))
        self._epoch_start_dataloader_state = copy.deepcopy(epoch_start_state)
        self._iter = enumerate(self._train_dataloader)

    def get_epoch_start_dataloader_state(self) -> dict:
        """Return the stable sampler state used to start the current epoch."""

        return copy.deepcopy(self._epoch_start_dataloader_state)

    async def reset_at_epoch_end(self) -> None:
        async with self._lock:
            # Construct the next iterator from the dataloader's current sampler
            # RNG state. Reloading the construction-time snapshot here repeated
            # the exact same task order every epoch, so async finish-time tails
            # could systematically discard the same slow/hard prompts.
            self._iter = enumerate(self._train_dataloader)
            # StatefulDataLoader chooses the next shuffled order when its new
            # iterator is constructed. Capture the state after construction,
            # but before the first item is drawn, so resume replays that order.
            self._epoch_start_dataloader_state = copy.deepcopy(
                self._train_dataloader.state_dict()
            )
            self._consumed_data_uids.clear()
            self._filtered_data_uids.clear()
            self._exhausted = False

    async def get_next_non_consumed_data(self):
        """
        Return the next batch of training data.

        If we loaded from a checkpoint, it will skip the already-consumed data. Returns None if the dataloader is exhausted.
        """
        assert self._iter is not None and self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            try:
                while True:
                    # Keep polling until we get a non-consumed data or the dataloader is exhausted.
                    iter_idx, rand_prompts = next(self._iter)
                    if iter_idx >= self._effective_dataloader_length:
                        raise StopIteration
                    uid = rand_prompts[0]["uid"]
                    if uid not in self._consumed_data_uids:
                        return rand_prompts
            except StopIteration:
                self._exhausted = True
                return None

    async def mark_consumed_uids(self, uids: Iterable[str]) -> None:
        """Mark UIDs as trained on (and hence consumed)."""
        assert self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            for uid in uids:
                assert uid not in self._consumed_data_uids, "Duplicate UID found in mini-batch"
                self._consumed_data_uids.add(uid)

    async def mark_filtered_uids(self, uids: Iterable[str]) -> None:
        """Mark UIDs as dropped (not trained on): added to the do-not-redraw set and recorded as
        filtered so they are skipped on resume and excluded from the trained-step count."""
        assert self._lock is not None, "Dataloader not initialized; call reset() first"
        async with self._lock:
            for uid in uids:
                assert uid not in self._consumed_data_uids, "Duplicate UID found in mini-batch"
                self._consumed_data_uids.add(uid)
                self._filtered_data_uids.add(uid)

    def get_consumed_uids_list(self) -> List[str]:
        return list(self._consumed_data_uids)

    def get_filtered_uids_list(self) -> List[str]:
        return list(self._filtered_data_uids)

    def num_trained(self) -> int:
        """Number of UIDs consumed by training (excludes filtered/dropped UIDs)."""
        return len(self._consumed_data_uids) - len(self._filtered_data_uids)


class FullyAsyncRayPPOTrainer(RayPPOTrainer):
    def __init__(self, *args, **kwargs):
        # Extract cfg before base init so we can initialize async-specific knobs used by our overrides.
        cfg = kwargs.get("cfg", args[0] if len(args) > 0 else None)
        assert cfg is not None, "cfg must be provided to FullyAsyncRayPPOTrainer"

        # Initialize async-specific knobs
        self.num_parallel_generation_workers = cfg.trainer.fully_async.num_parallel_generation_workers
        self.mini_batch_size = cfg.trainer.policy_mini_batch_size
        self.max_staleness_steps = cfg.trainer.fully_async.max_staleness_steps
        self.sample_full_batch = cfg.trainer.fully_async.sample_full_batch

        self._phase_gauge = TrainingPhaseGauge()

        self._gen_buffer_maxsize = self.mini_batch_size * (self.max_staleness_steps + 1)
        self._loop_gauges = ScalarGauges()
        self._loop_gauges.set(
            "skyrl_mini_batch_size",
            self.mini_batch_size,
            "Generation groups consumed per training step.",
        )
        self._loop_gauges.set(
            "skyrl_gen_buffer_maxsize",
            self._gen_buffer_maxsize,
            "Staleness-bounded generation-buffer capacity.",
        )

        assert (
            # otherwise wasted throughput
            self.mini_batch_size <= self.num_parallel_generation_workers
            and
            # otherwise would never use all workers due to capacity constraint
            self.num_parallel_generation_workers <= self.mini_batch_size * (self.max_staleness_steps + 1)
        ), (
            "Invalid num_parallel_generation_workers, the following must hold: "
            "mini_batch_size <= num_parallel_generation_workers <= mini_batch_size * (max_staleness_steps + 1). Got: "
            f"{self.mini_batch_size=}, {self.num_parallel_generation_workers=}, {self.max_staleness_steps=}"
        )

        # Initialize base trainer
        super().__init__(*args, **kwargs)

        # Some async-specific validations
        assert (
            self.cfg.trainer.fully_async.enabled
        ), "trainer.fully_async.enabled must be True when using the fully async trainer."
        assert (
            self.cfg.trainer.train_batch_size == self.cfg.trainer.policy_mini_batch_size
        ), "train_batch_size must equal policy_mini_batch_size for fully async training"
        assert (
            self.cfg.trainer.algorithm.dynamic_sampling.type is None
        ), "dynamic sampling is not supported for fully async training yet."
        if self.sample_full_batch:
            assert self.cfg.trainer.algorithm.zero_variance_filter, (
                "trainer.fully_async.sample_full_batch=True requires trainer.algorithm.zero_variance_filter=True "
                "(it is the async-native equivalent of dynamic_sampling='filter')."
            )
        assert (
            not self.cfg.generator.batched
        ), "batched is not supported for fully async training since a batched generate() call does not support pause/continue."
        # TODO(Charlie): we can support it, just multi-turn partial rollout but synchronous.
        assert not self.colocate_all, "colocate_all is not supported for async training yet."
        # Ensure we're using a policy loss that doesn't depend on pi_old ~= pi_rollout
        loss_type = self.cfg.trainer.algorithm.policy_loss_type
        if loss_type == PolicyLossType.CISPO and self.cfg.trainer.algorithm.cispo.cispo_anchor == "rollout":
            optimizes_against_rollout = True
        else:
            optimizes_against_rollout = loss_type not in LOSSES_WITH_OLD_LOGPROBS
        assert optimizes_against_rollout, (
            f"Found trainer.algorithm.policy_loss_type={loss_type} in "
            f"{sorted([loss.value for loss in LOSSES_WITH_OLD_LOGPROBS])}. Fully async training should use "
            "rollout logprobs (i.e. rollout_is, dppo, or cispo with cispo.cispo_anchor='rollout') instead "
            "of recomputing logprobs, since stale policies are not kept for logprob computation."
        )

        # TODO(Charlie): need to assert we are doing TIS and returning logprobs

        # Async-specific states
        self.async_train_dataloader = _AsyncDataloader(self.train_dataloader, self.mini_batch_size)
        self._staleness_manager = _AsyncStalenessManager(
            max_concurrent_generation_groups=self.num_parallel_generation_workers,
            mini_batch_size=self.mini_batch_size,
            max_staleness_steps=self.max_staleness_steps,
        )

    def _build_train_dataloader_and_compute_training_steps(self):
        """
        Overrides to build dataloader for fully async training. See `_AsyncDataloader` for more details.
        """
        self.train_dataloader = build_dataloader(self.cfg, self.train_dataset, is_train=True, is_fully_async=True)
        self.num_steps_per_epoch = len(self.train_dataloader) // self.mini_batch_size
        self.total_training_steps = self.num_steps_per_epoch * self.cfg.trainer.epochs
        if self.cfg.trainer.max_training_steps is not None:
            self.total_training_steps = min(self.total_training_steps, self.cfg.trainer.max_training_steps)
        logger.info(f"Length of train_dataloader: {len(self.train_dataloader)}")
        logger.info(f"Number of steps per epoch: {self.num_steps_per_epoch}")
        logger.info(f"Total training steps: {self.total_training_steps}")

    async def train(self):
        """Run the fully-async loop with whole-lifecycle status protection."""

        self._trainer_status_callback_loop = asyncio.get_running_loop()
        self._trainer_status_callback_thread_id = threading.get_ident()
        try:
            await self._train_impl()
        except BaseException as exc:
            emit_progress_event(
                "training_run_failed",
                global_step=getattr(self, "global_step", 0),
                total_steps=getattr(self, "total_training_steps", None),
                error_type=type(exc).__name__,
            )
            # Status callbacks are user code. A failure callback must not mask
            # the exception that actually stopped paid work.
            try:
                self._report_trainer_status(
                    "failed",
                    detail=f"{type(exc).__name__}: training aborted",
                    policy_version=getattr(self.inference_engine_client, "weight_version", None),
                )
            except BaseException:
                logger.exception("Trainer status callback failed while reporting a run failure")
            if self._ray_gpu_monitor is not None and getattr(self._ray_gpu_monitor, "_running", False):
                try:
                    self._ray_gpu_monitor.stop()
                except BaseException:
                    logger.exception("Ray GPU monitor cleanup failed while reporting a run failure")
            raise
        finally:
            self._trainer_status_callback_loop = None
            self._trainer_status_callback_thread_id = None

    async def _train_impl(self):
        """
        Main fully async training loop for PPO
        """
        self.global_step = 0
        self.epoch = 0
        resumed_start_epoch = None
        last_completed_step = 0
        last_checkpoint_step = None

        # Load checkpoint state if resumption is enabled. Also load the data UIDs that are already trained on.
        if self.resume_mode != ResumeMode.NONE:
            with Timer("load_checkpoints"):
                (
                    self.global_step,
                    _,
                    loaded_consumed_data_uids_set,
                    loaded_filtered_data_uids_set,
                    loaded_epoch,
                    loaded_epoch_start_dataloader_state,
                ) = self.load_checkpoints()
                logger.info(f"Resumed training from global_step {self.global_step}")
                last_completed_step = self.global_step
                if self.global_step > 0:
                    last_checkpoint_step = self.global_step
                if self.global_step > 0:
                    # Set async dataloader manager and staleness manager to the loaded state.
                    self.async_train_dataloader.load_state_from_checkpoint(
                        loaded_consumed_data_uids_set,
                        loaded_filtered_data_uids_set,
                        loaded_epoch_start_dataloader_state,
                    )
                    self._staleness_manager.load_state_from_checkpoint(
                        self.global_step + 1
                    )  # +1 due to we haven't incremented yet
                    # Only trained UIDs map to completed steps (filtered UIDs are extra consumption),
                    # so validate the trained count is a whole number of steps.
                    num_trained_loaded = len(loaded_consumed_data_uids_set) - len(loaded_filtered_data_uids_set)
                    assert num_trained_loaded % self.mini_batch_size == 0, (
                        "Loaded trained (consumed minus filtered) data UIDs must be a multiple of "
                        f"mini_batch_size={self.mini_batch_size}. Got: {num_trained_loaded}"
                    )
                    # Use the persisted epoch; fall back to deriving it for pre-sample_full_batch
                    # checkpoints (where global_step stays aligned to epoch boundaries).
                    resumed_start_epoch = (
                        loaded_epoch if loaded_epoch is not None else self.global_step // self.num_steps_per_epoch
                    )

        emit_progress_event(
            "training_run_started",
            global_step=self.global_step,
            total_steps=self.total_training_steps,
            batch_group_target=self.mini_batch_size,
            group_size=self.cfg.generator.n_samples_per_prompt,
            resumed=self.global_step > 0,
        )
        start_epoch = resumed_start_epoch if resumed_start_epoch is not None else 0
        self._current_epoch = start_epoch
        self._training_control.reset()
        self._report_trainer_status(
            "initializing",
            detail="initializing weight synchronization state",
        )

        # Initialize weight sync state
        emit_progress_event("weight_sync_state_init_started", global_step=self.global_step)
        with Timer("init_weight_sync_state"):
            self.init_weight_sync_state()
        emit_progress_event("weight_sync_state_init_finished", global_step=self.global_step)

        # sync weights to inference engines
        self._report_trainer_status(
            "syncing_weights",
            detail="publishing initial policy weights to rollout engines",
            policy_version=getattr(self.inference_engine_client, "weight_version", None),
        )
        emit_progress_event("weight_sync_started", global_step=self.global_step, initial=True)
        with Timer("sync_weights_to_inference_engines"):
            await self.dispatch.save_weights_for_sampler()
        emit_progress_event("weight_sync_finished", global_step=self.global_step, initial=True)
        self._report_trainer_status(
            "idle",
            detail="initial policy weights are ready",
            policy_version=getattr(self.inference_engine_client, "weight_version", None),
        )
        # Match RayPPOTrainer's callback contract: training starts only after
        # checkpoint restoration and the initial sampler weight publication.
        self._fire("on_train_start")

        # Per-step GPU utilization to the tracker. The base loop starts, flushes, and stops the
        # monitor itself. The async loop overrides train() and must wire it here.
        if self._ray_gpu_monitor is not None:
            self._ray_gpu_monitor.start()

        # Eval before training
        if self.cfg.trainer.eval_interval > 0 and self.cfg.trainer.eval_before_train and self.global_step == 0:
            self._report_trainer_status("evaluating", detail="step-0 evaluation")
            self._fire("on_eval_start")
            with self._phase_gauge.timed_phase("eval", self.all_timings):
                eval_metrics = await self.eval()
                self._fire("on_eval_end", metrics=eval_metrics)
                self._fire("on_log", logs=eval_metrics)
                self.tracker.log(eval_metrics, step=self.global_step, commit=True)

        # main training loop
        pbar = tqdm(
            total=self.total_training_steps,
            initial=self.global_step,
            desc="Training Step Progress",
        )
        self.global_step += 1  # start training at global_step 1
        stop_training = False
        generation_supervisor: Optional[asyncio.Task[None]] = None
        self._profiler_start()
        try:
            for epoch in range(start_epoch, self.cfg.trainer.epochs):
                self.epoch = epoch
                self._current_epoch = epoch
                self._fire("on_epoch_start")
                # 0. Per-epoch prologue. Note that we do not do any cross-epoch asynchrony here.

                # Buffer of completed generation, size bounded by capacity - consumed = B * (max_staleness_steps + 1)
                generation_output_group_buffer = asyncio.Queue[GeneratedOutputGroup](maxsize=self._gen_buffer_maxsize)

                # Structured concurrency keeps worker failures observable: one worker error cancels its
                # siblings and completes this supervisor with an ExceptionGroup. Buffer waits below race
                # the supervisor so a failed producer cannot leave the trainer blocked forever.
                generation_supervisor = asyncio.create_task(
                    self._run_generation_task_group(generation_output_group_buffer)
                )

                # Steps trained in THIS epoch (not global_step % num_steps_per_epoch: sample_full_batch can
                # end an epoch early, drifting global_step out of epoch alignment). On resume the dataloader
                # already reflects this epoch's trained steps. The range below is just an upper bound.
                trained_steps_this_epoch = self.async_train_dataloader.num_trained() // self.mini_batch_size
                for _step_idx in range(self.global_step, (1 + epoch) * self.num_steps_per_epoch + 1):
                    self._report_trainer_status(
                        "waiting_for_rollouts",
                        detail=f"collecting {self.mini_batch_size} accepted groups",
                        policy_version=getattr(self.inference_engine_client, "weight_version", None),
                    )
                    emit_progress_event(
                        "training_step_started",
                        global_step=self.global_step,
                        total_steps=self.total_training_steps,
                        epoch=epoch,
                        batch_group_target=self.mini_batch_size,
                        group_size=self.cfg.generator.n_samples_per_prompt,
                    )
                    with Timer("step", self.all_timings):
                        self._loop_gauges.set(
                            "skyrl_gen_buffer_qsize",
                            generation_output_group_buffer.qsize(),
                            "Completed generation groups buffered at step start.",
                        )

                        # 1. Wait until we have a full mini-batch buffered (dropping zero-variance groups if
                        # sample_full_batch).
                        (
                            cur_generation_group_mini_batch,
                            cur_dropped_groups,
                            epoch_exhausted,
                        ) = await self._collect_generation_mini_batch(
                            generation_output_group_buffer, generation_supervisor
                        )

                        # A worker can fail just as the final group is dequeued. Check again before
                        # entering synchronous post-processing or provider training work.
                        await self._raise_generation_task_group_error(generation_supervisor)

                        if epoch_exhausted:
                            # Exhausted mid mini-batch: discard the partial batch (marked consumed so it
                            # isn't regenerated on resume) and end the epoch early.
                            if cur_generation_group_mini_batch:
                                for _ in cur_generation_group_mini_batch:
                                    await self._staleness_manager.on_rollout_filtered()
                                await self.async_train_dataloader.mark_filtered_uids(
                                    [g.uid for g in cur_generation_group_mini_batch]
                                )
                                logger.warning(
                                    f"sample_full_batch: epoch {epoch} exhausted with a partial mini-batch of "
                                    f"{len(cur_generation_group_mini_batch)} group(s); discarding and ending the epoch."
                                )
                            # Save the end-of-epoch checkpoint the normal is_epoch_end path would have, since
                            # we break before reaching it.
                            if _needs_final_checkpoint(
                                self.cfg.trainer.ckpt_interval,
                                last_completed_step,
                                last_checkpoint_step,
                            ):
                                self._report_trainer_status(
                                    "checkpointing",
                                    detail=f"persisting global step {last_completed_step}",
                                    policy_version=getattr(self.inference_engine_client, "weight_version", None),
                                )
                                with self._phase_gauge.timed_phase("save_checkpoints", self.all_timings):
                                    checkpoint_path = await asyncio.to_thread(
                                        self.save_checkpoints,
                                        checkpoint_step=last_completed_step,
                                    )
                                self._fire("on_save", ckpt_path=checkpoint_path)
                                last_checkpoint_step = last_completed_step
                            if self.cfg.trainer.hf_save_interval > 0 and last_completed_step > 0:
                                with self._phase_gauge.timed_phase("save_hf_model", self.all_timings):
                                    await asyncio.to_thread(
                                        self.save_models,
                                        checkpoint_step=last_completed_step,
                                    )
                            break

                        if self.sample_full_batch:
                            # The collect loop returns exactly mini_batch_size kept groups here.
                            num_dropped = len(cur_dropped_groups)
                            keep_rate = self.mini_batch_size / (self.mini_batch_size + num_dropped)
                            self.all_metrics["async/num_groups_dropped"] = num_dropped
                            self.all_metrics["async/keep_rate"] = keep_rate
                            self._loop_gauges.set(
                                "skyrl_gen_group_keep_rate",
                                keep_rate,
                                "Fraction of drained groups kept while collecting the last mini-batch.",
                            )

                        # 2. Post-process the generated groups, aggregating to a single GeneratorOutput, and convert to training format.
                        self._report_trainer_status(
                            "preparing_batch",
                            detail=f"converting {len(cur_generation_group_mini_batch)} rollout groups",
                            policy_version=getattr(self.inference_engine_client, "weight_version", None),
                        )
                        with self._phase_gauge.timed_phase("convert_to_training_input", self.all_timings):
                            training_input = await asyncio.to_thread(
                                self.convert_generation_group_mini_batch_to_training_input,
                                cur_generation_group_mini_batch,
                                cur_dropped_groups,
                            )
                        await self._raise_generation_task_group_error(generation_supervisor)
                        self._fire("on_step_start", batch=training_input)

                        # 3. Run training and update consumed UIDs.
                        with self._phase_gauge.timed_phase("run_training", self.all_timings):
                            status = await self._run_training(training_input)
                            await self.async_train_dataloader.mark_consumed_uids(
                                [g.uid for g in cur_generation_group_mini_batch]
                            )
                            last_completed_step = self.global_step
                        self._fire("on_step_end", batch=training_input, metrics=status)
                        force_save = self._training_control.should_save
                        force_eval = self._training_control.should_evaluate
                        self._training_control.reset()

                        # 4. After training: pause generation, sync weights, resume.
                        self._report_trainer_status(
                            "syncing_weights",
                            detail="pausing rollout engines and publishing updated policy weights",
                            policy_version=getattr(self.inference_engine_client, "weight_version", None),
                        )
                        emit_progress_event("weight_sync_started", global_step=self.global_step, initial=False)
                        with self._phase_gauge.timed_phase("sync_weights", self.all_timings):
                            await self.dispatch.save_weights_for_sampler()
                        # The outer timer includes pause/resume coordinator overhead;
                        # retain the dispatcher's transfer-only timing alongside it.
                        self.all_timings.update(self.dispatch.get_timing_metrics())
                        emit_progress_event("weight_sync_finished", global_step=self.global_step, initial=False)
                        self._report_trainer_status(
                            "idle",
                            detail="updated policy weights are available to rollout engines",
                            policy_version=getattr(self.inference_engine_client, "weight_version", None),
                        )

                    # A training step completed: count it for this epoch's bookkeeping.
                    trained_steps_this_epoch += 1

                    # One profiler step per async global step.
                    self._profiler_step()

                    # 5. Set logs for this training step.
                    logger.info(status)
                    self.all_metrics.update(
                        {
                            "trainer/epoch": epoch,
                            "trainer/global_step": self.global_step,
                        }
                    )
                    pbar.update(1)
                    emit_progress_event(
                        "training_step_finished",
                        global_step=self.global_step,
                        total_steps=self.total_training_steps,
                        epoch=epoch,
                    )

                    # 6. Eval. At interval and at the last step.
                    # NOTE(Charlie): eval does not overlap with training, but overlaps with generation.
                    interval_eval = self.cfg.trainer.eval_interval > 0 and (
                        self.global_step % self.cfg.trainer.eval_interval == 0
                        or self.global_step == self.total_training_steps
                    )
                    if force_eval or interval_eval:
                        self._report_trainer_status("evaluating", detail="evaluation rollout and grading")
                        self._fire("on_eval_start")
                        with self._phase_gauge.timed_phase("eval", self.all_timings):
                            eval_metrics = await self.eval()
                            self.all_metrics.update(eval_metrics)
                        self._fire("on_eval_end", metrics=eval_metrics)

                    # Log metrics for this step after evaluation
                    self._fire("on_log", logs=self.all_metrics)
                    self.tracker.log(self.all_metrics, step=self.global_step, commit=False)
                    self.all_metrics = {}

                    # 7. Checkpointing. At interval and at the last step of each epoch.
                    is_epoch_end = trained_steps_this_epoch == self.num_steps_per_epoch
                    interval_checkpoint = self.cfg.trainer.ckpt_interval > 0 and (
                        is_epoch_end or self.global_step % self.cfg.trainer.ckpt_interval == 0
                    )
                    if force_save or interval_checkpoint:
                        self._report_trainer_status(
                            "checkpointing",
                            detail=f"persisting global step {last_completed_step}",
                            policy_version=getattr(self.inference_engine_client, "weight_version", None),
                        )
                        with self._phase_gauge.timed_phase("save_checkpoints", self.all_timings):
                            checkpoint_path = await asyncio.to_thread(
                                self.save_checkpoints,
                                checkpoint_step=last_completed_step,
                            )
                        self._fire("on_save", ckpt_path=checkpoint_path)
                        last_checkpoint_step = last_completed_step
                    if self.cfg.trainer.hf_save_interval > 0:
                        if is_epoch_end or self.global_step % self.cfg.trainer.hf_save_interval == 0:
                            with self._phase_gauge.timed_phase("save_hf_model", self.all_timings):
                                await asyncio.to_thread(
                                    self.save_models,
                                    checkpoint_step=last_completed_step,
                                )

                    timing_payload = {"timing/" + k: v for k, v in self.all_timings.items()}
                    if self._ray_gpu_monitor is not None:
                        timing_payload.update(self._ray_gpu_monitor.flush())
                    if self._vllm_metrics_scraper is not None:
                        timing_payload.update(await self._vllm_metrics_scraper.sample())
                    self.tracker.log(timing_payload, step=self.global_step, commit=True)
                    self.all_timings = {}

                    next_global_step, reached_max_training_steps = _advance_global_step_after_training(
                        self.global_step, self.cfg.trainer.max_training_steps
                    )
                    if reached_max_training_steps:
                        logger.info(
                            f"Reached max_training_steps={self.cfg.trainer.max_training_steps}, stopping early."
                        )
                        await self._stop_generation_task_group(generation_supervisor)
                        generation_supervisor = None
                        stop_training = True
                        break

                    self.global_step = next_global_step

                    # 8. Notify generation workers that the capacity has increased, unblocking them.
                    await self._staleness_manager.notify_capacity_change(self.global_step)
                    # Only trained UIDs map to completed steps; filtered/dropped UIDs are extra consumption.
                    expected_trained_in_epoch = self.mini_batch_size * trained_steps_this_epoch
                    actual_trained_in_epoch = self.async_train_dataloader.num_trained()
                    assert actual_trained_in_epoch == expected_trained_in_epoch, (
                        "Unexpected number of trained (consumed minus filtered) data UIDs. Got: "
                        f"{actual_trained_in_epoch} != {expected_trained_in_epoch}"
                    )

                if stop_training:
                    self._fire("on_epoch_end")
                    break

                # 9. Per-epoch epilogue.
                if self.cfg.trainer.update_ref_every_epoch and self.ref_model is not None:
                    with Timer("update_ref_with_policy", self.all_timings):
                        await asyncio.to_thread(self.update_ref_with_policy)

                # Stop any workers still waiting on capacity at the epoch boundary. If a worker
                # failed concurrently, propagate its TaskGroup error instead of swallowing it.
                await self._stop_generation_task_group(generation_supervisor)
                generation_supervisor = None

                # Per-epoch reset/validation for data loading and staleness management
                assert (
                    generation_output_group_buffer.qsize() == 0
                ), f"We expect all generation output to be consumed by the training worker at end of an epoch, got {generation_output_group_buffer.qsize()}."
                await self.async_train_dataloader.reset_at_epoch_end()
                await self._staleness_manager.validate_state_at_epoch_end(self.global_step)

                # End of an epoch.
                self._fire("on_epoch_end")
        finally:
            # Also clean up workers when conversion, training, evaluation, or checkpointing raises.
            # Suppress the supervisor result here so it cannot mask the exception already propagating;
            # normal paths use _stop_generation_task_group, which does propagate worker failures.
            if generation_supervisor is not None:
                if not generation_supervisor.done():
                    generation_supervisor.cancel()
                await asyncio.gather(generation_supervisor, return_exceptions=True)
            self._profiler_stop()
            if self._ray_gpu_monitor is not None:
                self._ray_gpu_monitor.stop()

        pbar.close()

        if not stop_training:
            # All epochs completed: advance past the last epoch so resuming from the final checkpoint
            # does not redo the last epoch (whose consumed UIDs were cleared at its epoch end).
            self.epoch = self.cfg.trainer.epochs

        # Safety net: save the final state unless this exact step was already
        # persisted by the interval/epoch path.
        if _needs_final_checkpoint(
            self.cfg.trainer.ckpt_interval,
            last_completed_step,
            last_checkpoint_step,
        ):
            self._report_trainer_status(
                "checkpointing",
                detail=f"persisting final global step {last_completed_step}",
                policy_version=getattr(self.inference_engine_client, "weight_version", None),
            )
            with self._phase_gauge.timed_phase("save_checkpoints", self.all_timings):
                checkpoint_path = await asyncio.to_thread(
                    self.save_checkpoints,
                    checkpoint_step=last_completed_step,
                )
                logger.info("Saved final checkpoint.")
            self._fire("on_save", ckpt_path=checkpoint_path)
        if self.cfg.trainer.hf_save_interval > 0 and last_completed_step > 0:
            with self._phase_gauge.timed_phase("save_hf_model", self.all_timings):
                await asyncio.to_thread(
                    self.save_models,
                    checkpoint_step=last_completed_step,
                )
                logger.info("Saved final model.")

        # Drain any in-flight async checkpoint write before teardown. Unconditional:
        # a save may have happened outside the periodic path. No-op when nothing is pending.
        self.dispatch.finalize_pending_saves("policy")
        if self.has_critic:
            self.dispatch.finalize_pending_saves("critic")

        if self._vllm_metrics_scraper is not None:
            await self._vllm_metrics_scraper.aclose()
        self._report_trainer_status("finalizing", detail="closing callbacks and experiment tracker")
        self._fire("on_train_end")
        self.tracker.finish()
        emit_progress_event(
            "training_run_finished",
            global_step=last_completed_step,
            total_steps=self.total_training_steps,
            stopped_early=stop_training,
        )
        self._report_trainer_status(
            "completed",
            detail="training loop and final persistence completed",
            policy_version=getattr(self.inference_engine_client, "weight_version", None),
        )
        logger.info("Training done!")

    async def _run_generation_task_group(self, buffer: asyncio.Queue) -> None:
        """Run all generation workers as one supervised unit.

        ``TaskGroup`` cancels the remaining workers when any worker raises and propagates the
        failure from this coroutine as an ``ExceptionGroup``. The training consumer observes this
        supervisor alongside the output buffer, so a producer failure cannot become a silent hang.
        """
        async with asyncio.TaskGroup() as task_group:
            for _ in range(self.num_parallel_generation_workers):
                task_group.create_task(self._run_generate_for_a_group_loop(buffer))

    @staticmethod
    async def _raise_generation_task_group_error(generation_supervisor: asyncio.Task[None]) -> None:
        """Propagate a completed generation supervisor's error, if any."""
        if generation_supervisor.done() and not generation_supervisor.cancelled():
            await generation_supervisor

    @staticmethod
    async def _stop_generation_task_group(generation_supervisor: asyncio.Task[None]) -> None:
        """Stop an epoch's generation workers without hiding a completed worker failure."""
        if generation_supervisor.done():
            if not generation_supervisor.cancelled():
                await generation_supervisor
            return

        generation_supervisor.cancel()
        await asyncio.gather(generation_supervisor, return_exceptions=True)
        # A worker may have failed just before cancellation reached the TaskGroup.
        if not generation_supervisor.cancelled():
            await generation_supervisor

    async def _drain_next_group(
        self, buffer: asyncio.Queue, generation_supervisor: asyncio.Task[None]
    ) -> Optional[GeneratedOutputGroup]:
        """Return the next generated group, or ``None`` after successful generation exhaustion.

        The buffer wait is raced against the generation TaskGroup supervisor. A worker failure is
        therefore raised immediately while the consumer is waiting, rather than being swallowed by
        a detached task and leaving the consumer blocked forever.
        """
        while True:
            # Prefer a producer error over already-buffered work. On successful exhaustion, drain
            # everything workers enqueued before returning None.
            if generation_supervisor.done():
                await FullyAsyncRayPPOTrainer._raise_generation_task_group_error(generation_supervisor)
                if buffer.empty():
                    return None
                return buffer.get_nowait()
            if not buffer.empty():
                return buffer.get_nowait()

            get_task = asyncio.create_task(buffer.get())
            try:
                done, _ = await asyncio.wait({get_task, generation_supervisor}, return_when=asyncio.FIRST_COMPLETED)
            except BaseException:
                get_task.cancel()
                await asyncio.gather(get_task, return_exceptions=True)
                raise

            if generation_supervisor in done:
                # If generation failed, clean up only the queue waiter before propagating the
                # supervisor's ExceptionGroup. Never cancel the shared supervisor from here.
                if not generation_supervisor.cancelled() and generation_supervisor.exception() is not None:
                    get_task.cancel()
                    await asyncio.gather(get_task, return_exceptions=True)
                    await generation_supervisor

                if get_task.done() and not get_task.cancelled():
                    return get_task.result()
                get_task.cancel()
                await asyncio.gather(get_task, return_exceptions=True)
                # Successful exhaustion may race an enqueue. Re-check the buffer before None.
                continue

            return get_task.result()

    def _should_keep_group(self, group: GeneratedOutputGroup) -> bool:
        """Whether a group has reward variance (train on it) vs. is zero-variance (drop it).

        Token-level rewards (``List[List[float]]``) are collapsed to a per-trajectory sum, like the rest
        of the trainer. Groups with fewer than two live trajectories have no group-relative signal and
        are dropped.
        """
        rewards = group.generator_output["rewards"]
        if rewards and isinstance(rewards[0], list):
            # Token-level rewards: collapse each trajectory to a scalar sequence reward.
            seq_rewards = [float(sum(r)) for r in rewards]
        else:
            seq_rewards = rewards
        kept_indices = zero_variance_filter(
            seq_rewards,
            [group.uid] * len(seq_rewards),
            loss_masks=group.generator_output["loss_masks"],
            tol=self.cfg.trainer.algorithm.zero_variance_filter_tol,
        )
        return len(kept_indices) > 0

    async def _collect_generation_mini_batch(
        self,
        generation_output_group_buffer: asyncio.Queue,
        generation_supervisor: asyncio.Task[None],
    ) -> Tuple[List[GeneratedOutputGroup], List[GeneratedOutputGroup], bool]:
        """Pull a full mini-batch of generated groups from the buffer.

        Without ``sample_full_batch``, blocks until ``mini_batch_size`` groups are available. With it,
        drops zero-variance groups (freeing their capacity, marking UIDs consumed) and keeps pulling
        until ``mini_batch_size`` non-zero-variance groups are collected, which can exhaust the epoch.

        Returns ``(kept_groups, dropped_groups, epoch_exhausted)``. On exhaustion the kept groups are a
        (possibly empty) partial batch to discard; dropped groups are kept for metrics only.
        """
        kept_groups: List[GeneratedOutputGroup] = []
        dropped_groups: List[GeneratedOutputGroup] = []
        epoch_exhausted = False
        # Buffer occupancy when this step starts waiting.
        self.all_metrics["async/gen_buffer_qsize_at_wait_start"] = generation_output_group_buffer.qsize()
        emit_progress_event(
            "generation_buffer_wait_started",
            global_step=self.global_step,
            batch_group_target=self.mini_batch_size,
            group_size=self.cfg.generator.n_samples_per_prompt,
            buffer_queue_size=generation_output_group_buffer.qsize(),
        )
        with self._phase_gauge.timed_phase("wait_for_generation_buffer", self.all_timings):
            buffer_pbar = tqdm(
                total=self.mini_batch_size,
                initial=0,
                desc="Generation Buffer Progress",
                position=1,
            )
            while len(kept_groups) < self.mini_batch_size:
                # We do finish-time FIFO here (not schedule-time FIFO).
                group = await self._drain_next_group(generation_output_group_buffer, generation_supervisor)
                if group is None:
                    if not self.sample_full_batch:
                        raise RuntimeError("Generation exhausted before producing a complete training mini-batch.")
                    epoch_exhausted = True
                    break

                if not self.sample_full_batch:
                    kept_groups.append(group)
                    buffer_pbar.update(1)
                    buffer_pbar.set_postfix({"buffer qsize": generation_output_group_buffer.qsize()})
                    emit_progress_event(
                        "group_accepted",
                        global_step=self.global_step,
                        group_uid=group.uid,
                        group_size=len(group.generator_output["response_ids"]),
                        accepted_count=len(kept_groups),
                        batch_group_target=self.mini_batch_size,
                        buffer_queue_size=generation_output_group_buffer.qsize(),
                        scheduled_global_step=group.global_step_when_scheduled,
                    )
                    continue

                try:
                    if self._should_keep_group(group):
                        kept_groups.append(group)
                        buffer_pbar.update(1)
                        buffer_pbar.set_postfix({"buffer qsize": generation_output_group_buffer.qsize()})
                        emit_progress_event(
                            "group_accepted",
                            global_step=self.global_step,
                            group_uid=group.uid,
                            group_size=len(group.generator_output["response_ids"]),
                            accepted_count=len(kept_groups),
                            batch_group_target=self.mini_batch_size,
                            buffer_queue_size=generation_output_group_buffer.qsize(),
                            scheduled_global_step=group.global_step_when_scheduled,
                        )
                    else:
                        # Drop the zero-variance group: give its capacity back to the producers and mark
                        # its UID consumed (skipped, not regenerated, on resume).
                        dropped_groups.append(group)
                        await self._staleness_manager.on_rollout_filtered()
                        await self.async_train_dataloader.mark_filtered_uids([group.uid])
                        emit_progress_event(
                            "group_filtered",
                            global_step=self.global_step,
                            group_uid=group.uid,
                            group_size=len(group.generator_output["response_ids"]),
                            filtered_count=len(dropped_groups),
                            reason="zero_variance",
                            scheduled_global_step=group.global_step_when_scheduled,
                        )
                except Exception:
                    self._log_group_processing_error(group, len(kept_groups), len(dropped_groups))
                    raise
            buffer_pbar.close()
        emit_progress_event(
            "generation_buffer_wait_finished",
            global_step=self.global_step,
            accepted_count=len(kept_groups),
            filtered_count=len(dropped_groups),
            batch_group_target=self.mini_batch_size,
            buffer_queue_size=generation_output_group_buffer.qsize(),
            epoch_exhausted=epoch_exhausted,
        )
        return kept_groups, dropped_groups, epoch_exhausted

    @staticmethod
    def _log_group_processing_error(group: GeneratedOutputGroup, kept_so_far: int, dropped_so_far: int) -> None:
        """Log the offending group's reward / loss-mask shape before an error propagates."""
        go = group.generator_output
        rewards = go.get("rewards") if isinstance(go, dict) else None
        loss_masks = go.get("loss_masks") if isinstance(go, dict) else None
        logger.exception(
            "sample_full_batch: error processing generated group "
            f"(uid={group.uid}, kept_so_far={kept_so_far}, dropped_so_far={dropped_so_far}). "
            f"rewards type={type(rewards).__name__} "
            f"len={len(rewards) if hasattr(rewards, '__len__') else 'n/a'} "
            f"value={rewards!r}; "
            f"loss_masks type={type(loss_masks).__name__} "
            f"len={len(loss_masks) if hasattr(loss_masks, '__len__') else 'n/a'}"
        )

    async def _run_training(self, training_input: TrainingInputBatch):
        emit_progress_event("training_compute_started", global_step=self.global_step)
        # TODO(Charlie): share this code with the one-step-off async trainer.
        # inference and calculate values, log probs, rewards, kl divergence
        self._report_trainer_status(
            "recomputing_logprobs",
            detail="forward pass for rollout logprobs, values, and rewards",
        )
        with Timer("fwd_logprobs_values_reward", self.all_timings):
            training_input = await asyncio.to_thread(self.fwd_logprobs_values_reward, training_input)

        # calculate kl divergence and create experiences
        if self.cfg.trainer.algorithm.use_kl_in_reward:
            with Timer("apply_reward_kl_penalty", self.all_timings):
                training_input = self.apply_reward_kl_penalty(training_input)

        # calculate advantages and returns / along with tensorboard logging
        self._report_trainer_status(
            "computing_advantages",
            detail="computing returns and group-relative advantages",
        )
        with Timer("compute_advantages_and_returns", self.all_timings):
            training_input = self.compute_advantages_and_returns(training_input)
            # remove some unwanted keys
            for key in ["rewards"]:
                training_input.pop(key)
            training_input.metadata.pop("uids")

        if self.cfg.trainer.dump_data_batch:
            # dump data to file
            with Timer("dump_data_batch"):
                self.dump_data(
                    training_input,
                    file_name=f"global_step_{self.global_step}_training_input",
                )

        # train policy/critic model
        with Timer("train_critic_and_policy", self.all_timings):
            status = await asyncio.to_thread(self.train_critic_and_policy, training_input)

        emit_progress_event("training_compute_finished", global_step=self.global_step)
        return status

    async def _run_generate_for_a_group_loop(self, generation_output_group_buffer: asyncio.Queue):
        """
        Generator worker: repeatedly pulls the next prompt (possibly blocked by staleness control),
        generates one single generation group, respecting a pause/resume event, and enqueues the result.
        """
        slot_acquired = False
        active_group_uid: str | None = None
        active_group_step: int | None = None
        try:
            while True:
                # 0. Pull next batch from dataloader. If returns None, then dataloader is exhausted.
                rand_prompts = await self.async_train_dataloader.get_next_non_consumed_data()
                if rand_prompts is None:
                    return

                # 1. Prepare generator input
                assert len(rand_prompts) == 1
                generator_input, uids = prepare_generator_input(
                    rand_prompts,
                    self.cfg.generator.n_samples_per_prompt,
                    get_sampling_params_for_backend(
                        self.cfg.generator.inference_engine.backend,
                        self.cfg.generator.sampling_params,
                    ),
                    self.cfg.environment.env_class,
                    "train",
                    self.global_step,
                )
                assert all(uid == uids[0] for uid in uids), "Expect all uids to be the same"

                # 2. Acquire capacity slot.
                await self._staleness_manager.acquire_submission_slot()
                slot_acquired = True

                # 3. Generate one rollout group
                global_step_at_start = self.global_step  # for staleness control
                active_group_uid = uids[0]
                active_group_step = global_step_at_start
                emit_progress_event(
                    "group_scheduled",
                    global_step=global_step_at_start,
                    group_uid=uids[0],
                    group_size=self.cfg.generator.n_samples_per_prompt,
                )

                group_start_time = time.monotonic()
                if "disable_tqdm" in inspect.signature(self.generator.generate).parameters:
                    # A workaround to disable tqdm for the SkyRLGymGenerator.generate method which will
                    # blast the console with each worker's progress bar.
                    cur_generator_output: GeneratorOutput = await self.generator.generate(
                        generator_input, disable_tqdm=True
                    )
                else:
                    cur_generator_output: GeneratorOutput = await self.generator.generate(generator_input)
                group_completion_time_s = time.monotonic() - group_start_time
                emit_progress_event(
                    "group_completed",
                    global_step=global_step_at_start,
                    group_uid=uids[0],
                    group_size=len(cur_generator_output["response_ids"]),
                    duration_s=group_completion_time_s,
                )

                # 4. Enqueue the completed group and mark accepted to free capacity slot.
                try:
                    generation_output_group_buffer.put_nowait(
                        GeneratedOutputGroup(
                            generator_output=cur_generator_output,
                            uid=uids[0],
                            global_step_when_scheduled=global_step_at_start,
                            group_completion_time_s=group_completion_time_s,
                            prompts=generator_input["prompts"],
                        )
                    )
                except asyncio.QueueFull:
                    raise AssertionError("Generation buffer should never be full given staleness control.")
                await self._staleness_manager.on_rollout_accepted()
                slot_acquired = False
                active_group_uid = None
                active_group_step = None
        except Exception:
            if active_group_uid is not None:
                emit_progress_event(
                    "group_failed",
                    global_step=active_group_step,
                    group_uid=active_group_uid,
                )
            logger.exception("Generator worker errored out")
            raise
        finally:
            # Both worker failures and normal TaskGroup cancellation must return a reserved slot.
            if slot_acquired:
                try:
                    await self._staleness_manager.on_rollout_rejected()
                except Exception:
                    logger.exception("Failed to release the generation worker's staleness slot")

    @staticmethod
    def _reprefix_metrics(metrics: dict, suffix: str) -> dict:
        """Re-prefix metric keys into a separate view (``generate/X`` -> ``generate_<suffix>/X``),
        keeping the leading namespace so views group together in trackers."""
        out = {}
        for k, v in metrics.items():
            if "/" in k:
                prefix, rest = k.split("/", 1)
                out[f"{prefix}_{suffix}/{rest}"] = v
            else:
                out[f"{suffix}/{k}"] = v
        return out

    def _get_group_staleness(self, generated_group: GeneratedOutputGroup) -> tuple[int, list[int]]:
        """Return exact hosted staleness, or the scheduler-step fallback."""

        group_sampler_versions = generated_group.generator_output.get("sampler_versions")
        if group_sampler_versions is None:
            return self.global_step - generated_group.global_step_when_scheduled, []

        group_size = len(generated_group.generator_output["response_ids"])
        if len(group_sampler_versions) != group_size:
            raise ValueError(
                "sampler_versions must have one entry per generated response: "
                f"{len(group_sampler_versions)} != {group_size}"
            )
        current_sampler_version = getattr(self.inference_engine_client, "weight_version", None)
        if current_sampler_version is None:
            raise ValueError(
                "Generator output reported sampler_versions but the inference client has no weight_version"
            )
        versions = [int(version) for version in group_sampler_versions]
        per_response_staleness = [int(current_sampler_version) - version for version in versions]
        if any(value < 0 for value in per_response_staleness):
            raise ValueError(
                "A rollout reported a sampler version newer than the currently "
                f"published version {current_sampler_version}: {versions}"
            )

        # A group may contain requests admitted on adjacent immutable Tinker
        # clients. Its oldest response determines group-level staleness.
        return max(per_response_staleness), versions

    def convert_generation_group_mini_batch_to_training_input(
        self,
        cur_generation_group_mini_batch: List[GeneratedOutputGroup],
        dropped_groups: Optional[List[GeneratedOutputGroup]] = None,
    ) -> TrainingInputBatch:
        """Concatenate the mini-batch of generated groups and convert to a TrainingInputBatch.

        ``dropped_groups`` (zero-variance groups dropped this step under ``sample_full_batch``) are not
        trained on, but are folded into the reward/generation metrics to keep them comparable across runs.
        """
        dropped_groups = dropped_groups or []
        generator_outputs = []
        # Prompts for the kept groups, kept parallel to the concatenated `generator_output` so the
        # trajectory logger can render prompt + response (mirrors the sync trainer's use of
        # `generator_input["prompts"]`).
        prompts: List[Any] = []
        uids = []
        stalenesses = []
        staleness_violation_count = 0
        sampler_versions = []
        # Per-group completion times (seconds) and the intra-group spread (std and coefficient of
        # variation) of per-trajectory completion times. Helpful to understand tail latency
        group_completion_times: List[float] = []
        intra_group_stds: List[float] = []
        intra_group_cvs: List[float] = []
        for cur_generated_output_group in cur_generation_group_mini_batch:
            cur_staleness, exact_versions = self._get_group_staleness(cur_generated_output_group)
            sampler_versions.extend(exact_versions)
            stalenesses.append(cur_staleness)
            generator_outputs.append(cur_generated_output_group.generator_output)
            if cur_generated_output_group.prompts is not None:
                prompts.extend(cur_generated_output_group.prompts)

            # Collect per-group / per-trajectory completion-time stats for this group.
            if cur_generated_output_group.group_completion_time_s is not None:
                group_completion_times.append(cur_generated_output_group.group_completion_time_s)
            intra_group_std, intra_group_cv = get_intra_group_completion_time_std_cv(
                cur_generated_output_group.generator_output
            )
            if intra_group_std is not None:
                intra_group_stds.append(intra_group_std)
            if intra_group_cv is not None:
                intra_group_cvs.append(intra_group_cv)

            # NOTE(Charlie): for step-wise training each group can contain a variable number of entries
            # (n_samples_per_prompt * variable turns_per_trajectory), so the uid fanout is per-group.
            group_size = len(cur_generated_output_group.generator_output["response_ids"])
            uids.extend([cur_generated_output_group.uid] * group_size)

            # Check staleness violation.
            if cur_staleness > self.max_staleness_steps:
                # TODO(Charlie): should we drop, drop and resample, or just log?
                logger.warning(
                    "Staleness control violated despite using AsyncStalenessManager: "
                    f"cur_staleness={cur_staleness}, max_staleness_steps={self.max_staleness_steps}.\n"
                    "If this happens too often, consider increasing max_staleness_steps, adjusting "
                    "trainer.fully_async.num_parallel_generation_workers, or adjusting generation-training GPU allocation.\n"
                    "See https://docs.skyrl.ai/docs/tutorials/fully_async#async-staleness-manager for more details."
                )
                staleness_violation_count += 1

        generator_output = concatenate_generator_outputs(
            generator_outputs, step_wise=self.cfg.generator.step_wise_trajectories
        )
        kept_rollout_metrics = generator_output["rollout_metrics"]
        assert kept_rollout_metrics is not None, "Rollout metrics should be non-null."

        # Kept + dropped view for the headline reward/generation metrics, so they stay comparable
        # across runs regardless of filtering. Dropped groups are used for metrics only, never trained.
        metrics_generator_output = None
        metrics_uids = None
        if dropped_groups:
            metrics_generator_output = concatenate_generator_outputs(
                generator_outputs + [g.generator_output for g in dropped_groups],
                step_wise=self.cfg.generator.step_wise_trajectories,
            )
            metrics_uids = []
            for g in list(cur_generation_group_mini_batch) + dropped_groups:
                metrics_uids.extend([g.uid] * len(g.generator_output["response_ids"]))

        # Headline generation (rollout) metrics: over kept + dropped when sample_full_batch dropped groups.
        rollout_metrics_source = metrics_generator_output if metrics_generator_output is not None else generator_output
        self.all_metrics.update(rollout_metrics_source["rollout_metrics"])

        group_completion_metrics = get_group_completion_metrics(
            group_completion_times, intra_group_stds, intra_group_cvs
        )

        if dropped_groups:
            # Also split generation metrics by kept vs dropped, plus reward metrics for the dropped
            # groups. (Kept reward metrics are uninformative -- pass@n ~1 -- and loss/avg_final_rewards
            # already covers the trained set.)
            dropped_generator_output = concatenate_generator_outputs(
                [g.generator_output for g in dropped_groups],
                step_wise=self.cfg.generator.step_wise_trajectories,
            )
            self.all_metrics.update(self._reprefix_metrics(kept_rollout_metrics, "kept"))
            self.all_metrics.update(self._reprefix_metrics(dropped_generator_output["rollout_metrics"], "dropped"))
            dropped_uids = [g.uid for g in dropped_groups for _ in range(len(g.generator_output["response_ids"]))]
            dropped_reward = get_metrics_from_generator_output(dropped_generator_output, dropped_uids)

            n_samples_per_prompt = self.cfg.generator.n_samples_per_prompt
            self.all_metrics.update(
                {
                    f"reward_dropped/avg_pass_at_{n_samples_per_prompt}": dropped_reward["pass_at_n"],
                    "reward_dropped/avg_raw_reward": dropped_reward["avg_score"],
                    "reward_dropped/mean_positive_reward": dropped_reward["mean_positive_reward"],
                }
            )
            dropped_generator_output.pop("rollout_metrics", None)

            # Per-group completion times and intra-group spread for dropped groups
            dropped_group_completion_times = []
            dropped_group_intra_group_stds = []
            dropped_group_intra_group_cvs = []
            for dropped_group in dropped_groups:
                if dropped_group.group_completion_time_s is not None:
                    dropped_group_completion_times.append(dropped_group.group_completion_time_s)
                intra_group_std, intra_group_cv = get_intra_group_completion_time_std_cv(dropped_group.generator_output)
                if intra_group_std is not None:
                    dropped_group_intra_group_stds.append(intra_group_std)
                if intra_group_cv is not None:
                    dropped_group_intra_group_cvs.append(intra_group_cv)

            dropped_metrics = get_group_completion_metrics(
                dropped_group_completion_times,
                dropped_group_intra_group_stds,
                dropped_group_intra_group_cvs,
            )

            self.all_metrics.update(self._reprefix_metrics(group_completion_metrics, "kept"))
            self.all_metrics.update(self._reprefix_metrics(dropped_metrics, "dropped"))

            merged_group_completion_times = group_completion_times + dropped_group_completion_times
            merged_intra_group_stds = intra_group_stds + dropped_group_intra_group_stds
            merged_intra_group_cvs = intra_group_cvs + dropped_group_intra_group_cvs
            # get merged metrics with kept + dropped groups
            group_completion_metrics = get_group_completion_metrics(
                merged_group_completion_times,
                merged_intra_group_stds,
                merged_intra_group_cvs,
            )

        self.all_metrics.update(group_completion_metrics)

        generator_output.pop("rollout_metrics", None)
        if metrics_generator_output is not None:
            metrics_generator_output.pop("rollout_metrics", None)

        # Log staleness statistics for this step
        self.all_metrics.update(
            {
                "async/staleness_mean": sum(stalenesses) / len(stalenesses),
                "async/staleness_max": max(stalenesses),
                "async/staleness_min": min(stalenesses),
                "async/staleness_ratio": sum(1 for s in stalenesses if s > 0) / len(stalenesses),
                "async/staleness_violation_count": staleness_violation_count,
            }
        )
        if sampler_versions:
            self.all_metrics.update(
                {
                    "async/sampler_version_min": min(sampler_versions),
                    "async/sampler_version_max": max(sampler_versions),
                    "async/current_sampler_version": int(self.inference_engine_client.weight_version),
                }
            )

        # Per-token reward conversion (kept groups only) + reward metrics over the kept+dropped view.
        generator_output, uids = self.postprocess_generator_output(
            generator_output,
            uids,
            metrics_generator_output=metrics_generator_output,
            metrics_uids=metrics_uids,
        )

        # print example just for debugging
        vis = self.tokenizer.decode(generator_output["response_ids"][0])
        logger.info(f"Example generated: {vis}")

        # Optionally upload up to `num_logger_train_samples` samples to tracker (mirrors the
        # synchronous trainer's train trajectory logging).
        if self.trajectory_logger is not None:
            with Timer("log_train_results"):
                self.trajectory_logger.log(
                    tracker=self.tracker,
                    num_samples=self.cfg.trainer.num_logger_train_samples,
                    prompts=prompts,
                    generator_output=generator_output,
                    tokenizer=self.tokenizer,
                    global_step=self.global_step,
                    wandb_key="trajectories/train",
                    include_idx=False,
                )

        return self.convert_to_training_input(generator_output, uids)

    def save_checkpoints(self, *, checkpoint_step: Optional[int] = None) -> str:
        """
        Extend base checkpointing by recording consumed UIDs for fully-async training.

        Otherwise, when resuming, there is no way to know which data has been trained on.
        Returns the checkpoint folder path (forwarded from the base implementation).
        """
        consumed_uids_list = (
            self.async_train_dataloader.get_consumed_uids_list()
        )  # read first to prevent race condition
        filtered_uids_list = self.async_train_dataloader.get_filtered_uids_list()
        epoch_start_dataloader_state = (
            self.async_train_dataloader.get_epoch_start_dataloader_state()
        )
        resolved_step = self.global_step if checkpoint_step is None else checkpoint_step
        emit_progress_event("checkpoint_started", global_step=resolved_step)
        # Save the common payload first, but do not publish ``latest`` until
        # the fully-async state below is also durable.
        global_step_folder = super().save_checkpoints(
            checkpoint_step=resolved_step,
            publish=False,
        )
        # Also save the consumed UIDs (do-not-redraw this epoch), the filtered subset (so dropped
        # prompts are skipped, not regenerated, on resume), and the epoch (not derivable from
        # global_step under sample_full_batch, where an epoch can end early).
        fully_async_state_path = os.path.join(global_step_folder, "fully_async_state.pt")
        fully_async_state = {
            "consumed_uids": consumed_uids_list,
            "filtered_uids": filtered_uids_list,
            "epoch": self.epoch,
            "epoch_start_dataloader_state": epoch_start_dataloader_state,
        }
        with io.open_file(fully_async_state_path, "wb") as f:
            torch.save(fully_async_state, f)
        logger.info(f"Saved fully-async state to {fully_async_state_path}")
        self._publish_checkpoint(resolved_step, global_step_folder)
        emit_progress_event(
            "checkpoint_finished",
            global_step=resolved_step,
            checkpoint_path=global_step_folder,
        )
        return global_step_folder

    def load_checkpoints(
        self,
    ) -> Tuple[
        int,
        str,
        Optional[Set[str]],
        Optional[Set[str]],
        Optional[int],
        Optional[dict],
    ]:
        """
        Load the base checkpoint without loading the dataloader state, and load the fully-async state.

        Returns the global step to resume from, the checkpoint path, the consumed data UIDs, the
        filtered (dropped, not trained on) data UIDs, and the epoch to resume in (None if the
        checkpoint predates epoch tracking, in which case the caller derives it from global_step),
        plus the current epoch's initial dataloader state when available.
        """
        global_step, checkpoint_path = super().load_checkpoints()
        if global_step == 0:
            return 0, checkpoint_path, None, None, None, None
        fully_async_state_path = os.path.join(checkpoint_path, "fully_async_state.pt")
        assert io.exists(fully_async_state_path), f"Fully-async state file not found at {fully_async_state_path}"
        with io.open_file(fully_async_state_path, "rb") as f:
            fully_async_state = torch.load(f, map_location="cpu", weights_only=False)
            assert "consumed_uids" in fully_async_state, "consumed_uids key not found in fully-async state"
            consumed_data_uids_set = set(fully_async_state["consumed_uids"])
            # Backward compatible with checkpoints saved before filtered UIDs / epoch were tracked.
            filtered_data_uids_set = set(fully_async_state.get("filtered_uids", []))
            epoch = fully_async_state.get("epoch", None)
            epoch_start_dataloader_state = fully_async_state.get(
                "epoch_start_dataloader_state"
            )
        logger.info(
            f"Loaded fully-async state with {len(consumed_data_uids_set)} consumed UIDs "
            f"({len(filtered_data_uids_set)} filtered), epoch={epoch}"
        )
        return (
            global_step,
            checkpoint_path,
            consumed_data_uids_set,
            filtered_data_uids_set,
            epoch,
            epoch_start_dataloader_state,
        )
